#
# (C) Copyright 2018 Nuxeo (http://nuxeo.com/) and others.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Contributors:
#     pierre
#

version: "2"
services:
  db:
    image: dockerpriv.nuxeo.com:443/oracle/database:18.3.0-ee
    ports:
      - 1521:1521
    environment:
      - ORACLE_SID=TESTDBNAME
      - ORACLE_PDB=oraclepdb
      - ORACLE_PWD=Adm!n-p4ssw0rd

  tests:
    image: dockerpriv.nuxeo.com:443/nuxeo/jenkins-slave
    volumes:
      - $WORKSPACE:$WORKSPACE
      - /var/run/docker.sock:/var/run/docker.sock:rw
    links:
      - db
    environment:
      - JAVA_OPTS=-Xms512m -Xmx3g
      - NX_DB_HOST=db
      - NX_DB_PORT=1521
      - NX_DB_ADMINNAME=TESTDBNAME
      - NX_DB_ADMINUSER=SYS
      - NX_DB_ADMINPASS=Adm!n-p4ssw0rd
      - NX_DB_USER=nuxeoUser
      - NX_DB_PASS=9Zp9fzX7
    command: /sbin/my_init -- su - jenkins -c "$TESTS_COMMAND"
